# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ubuntu:14.04
      - image: circleci/mongo:3.4.4
        command: [mongod, --smallfiles]

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: echo 'export PATH=$HOME/.meteor:$PATH' >> $BASH_ENV

      - run:
          command: meteor npm install
          name: install
          working_directory: src

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          command: MONGO_URL=localhost:27017/runner meteor test --once --driver-package meteortesting:mocha
          name: test
          working_directory: src
